# Monthly Price Data – Mini Project

## Project goals

- Load a real CSV file (`monthly.csv`) using pure Python.
- Parse raw text lines into clean date and price columns without using pandas.
- Convert the data into NumPy arrays for further analysis.
- Build a 2D NumPy table with rows of the form `[year, month, price]`.
- Practice basic text processing in Python (`strip`, `split`, loops, lists) and NumPy (`array`, `dtype`, `shape`).

In [28]:
import numpy as np
filename = "monthly.csv"
f = open(filename, "r")
lines = f.readlines()
f.close()

In [29]:
data_lines = lines[1:]

dates = []

for line in data_lines:
    parts = line.strip().split(",")
    date_str = parts[0] 
    dates.append(date_str) 

In [30]:

prices = []

for line in data_lines:
    parts = line.strip().split(",")
    price_str = parts[1]
    prices.append(price_str)

In [31]:
np_dates = np.array(dates)
np_prices = np.array(prices)
print(np_dates)
print(np_prices)

['1833-01' '1833-02' '1833-03' ... '2025-12' '2026-01' '2026-02']
['18.930' '18.930' '18.930' ... '4309.230' '4752.750' '5019.970']


In [32]:
years = []
months = []

for d in np_dates:
    y_str, m_str = d.split("-")
    years.append(int(y_str))
    months.append(int(m_str))

np_years = np.array(years)
np_months = np.array(months)

In [33]:
np_prices = np.array(prices, dtype= float)

In [34]:
table = np.column_stack ((np_years, np_months, np_prices))
print(table.shape)
print(table[:5])

(2318, 3)
[[1.833e+03 1.000e+00 1.893e+01]
 [1.833e+03 2.000e+00 1.893e+01]
 [1.833e+03 3.000e+00 1.893e+01]
 [1.833e+03 4.000e+00 1.893e+01]
 [1.833e+03 5.000e+00 1.893e+01]]


## Conclusions

- I successfully loaded the `monthly.csv` file and inspected the raw text lines.
- I parsed the file into separate `dates` and `prices` lists, then converted them to NumPy arrays.
- From the date strings (`YYYY-MM`) I extracted integer `year` and `month` columns.
- I built a 2D NumPy table `[year, month, price]` and verified its shape and first rows.
- Along the way I got more comfortable with string methods (`strip`, `split`), loops, list `append`, and NumPy `dtype=float`.